Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  end
  config.vm.box = "base"
    config.vm.define :firewall do |firewall|
    firewall.vm.box = "bento/centos-7"
    firewall.vm.hostname = "firewall"
    firewall.vm.network :private_network, ip: "192.168.50.3"
    firewall.vm.network :public_network, bridge: "Intel(R) Ethernet Connection (7) I219-V"
    firewall.vm.provision "shell", path: "firewall.sh"
  end
  config.vm.define :streama do |streama|
    streama.vm.box = "bento/centos-7"
    streama.vm.hostname = "streama"
    streama.vm.network :private_network, ip: "192.168.50.4"
    streama.vm.provision "shell", path: "streama.sh"
  end
end
